const PAYMENT_STATUS = {
  CREATED: "CREATED",
  AUTHORIZED: "AUTHORIZED",
  CAPTURED: "CAPTURED",
  FAILED: "FAILED",
  REFUNDED: "REFUNDED",
};

const PAYMENT_GATEWAY = {
  RAZORPAY: "RAZORPAY",
  CASHFREE: "CASHFREE",
};

module.exports = {
  PAYMENT_STATUS,
  PAYMENT_GATEWAY,
};
